[general]
live_config_reload = true

import = [
  "~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"


[window]
padding = { x = 10, y = 0 }
opacity = 0.95
blur = true

[scrolling]
history = 100000 # the max valid value

[font]
size = 13

normal = { family = "Zed Plex Mono", style = "Regular" }
bold = { family = "Zed Plex Mono", style = "Bold" }
italic = { family = "Zed Plex Mono", style = "Italic" }
bold_italic = { family = "Zed Plex Mono", style = "Bold Italic" }

[keyboard]
bindings = [

{ key = "C", mods = "Control|Shift", action = "Copy" },
{ key = "P", mods = "Control|Shift", action = "Paste" },


{ key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
{ key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },  # alacritty BUG

{ key = "T", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "Q", mods = "Control|Shift", action = "Quit" },

]


